title: Kuboaa
email: noreply@kuboaa.no
author: Kuboaa
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://kuboaa.no"
timezone: Europe/London
exclude: ["vendor", "*.nix", ".git", "_site"]
show_drafts: null
permalink: /:year/:month/:day/:title.html
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
